start_scheduled_post:
  every:
    - "30s"
  class: "StartScheduledPost"
  queue: start_scheduled_post
  description: "This will start a scheduled post if workers are available and post is eligible."

queue_unknown_posts_for_updating_status:
  every:
    - "20s"
  class: "UpdateStatuses"
  queue: update_statuses
  description: "This will hit facebook api and update status of post based on response."

update_captions_of_post:
  every:
    - "20s"
  class: "UpdateCaptions"
  queue: update_captions
  description: "This will hit facebook api and update caption of a free user's post."

end_subscription_of_users:
  every:
    - "4h"
  class: "ExpireSubscription"
  queue: "expire_subscription"