class Constant < ActiveRecord::Base
	MEMBER_POST_LIMIT = 1
  DONOR_POST_LIMIT = 1
  PREMIUM_POST_LIMIT = 1
  ULTIMATE_POST_LIMIT = 2
  ADMIN_POST_LIMIT = 10
  DONOR_COST = 20
  PREMIUM_COST = 30
  ULTIMATE_COST = 40
end
